.TH "TETZLE" "6" "October 2016"

.SH "NAME"
tetzle \- tetromino jigsaw puzzle game

.SH "SYNOPSIS"
.PP
.B tetzle
[\fB\-G\fR \fIversion\fR]

.SH "DESCRIPTION"
.PP
Tetzle is a jigsaw puzzle game that uses tetrominoes for the pieces. Any
image can be imported and used to create puzzles with a wide range of
sizes. Games are saved automatically, and you can select between currently
in progress games.

.SH "OPTIONS"
.TP
\fB\-G\fR \fIversion\fR, \fB\-\-graphics\-layer\fR\=\fIversion\fR
Attempt to use the specified \fBversion\fR of OpenGL. If the requested
version is larger than 2.1, Tetzle will default to the highest supported
version.

.SH "COPYRIGHT"
.PP
Copyright \(co 2016 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
