.TH TETZLE 6 "April 2021" "Tetzle 2.1.6" "Games Manual"

.SH "NAME"
tetzle \- tetromino jigsaw puzzle game

.SH "SYNOPSIS"
.B tetzle
[options]
.RI [ files ]

.SH "DESCRIPTION"
Tetzle is a jigsaw puzzle game that uses tetrominoes for the pieces. Any
image can be imported and used to create puzzles with a wide range of
sizes. Games are saved automatically, and you can select between currently
in progress games.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.
.TP
.BR "\-G VERSION" ", " "\-\-graphics\-layer=VERSION"
Attempt to use the specified \fBVERSION\fP of OpenGL. If the requested
version is larger than 2.1, Tetzle will default to the highest supported
version.
.TP
.I files
Images to add to the choose game dialog.

.SH "SEE ALSO"
.BR qt5options (7)

.SH "REPORTING BUGS"
Report bugs to <tetzle@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2008-2021 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
